#!/bin/sh
# *********************************
# Author        : seaice6
# Last modified : 2020-06-10 星期三 00:41:12
# Email         : lhb16@outlook.com
# Filename      : readme
# Description   : 
# *********************************

you need change the file name "molokai_vim" to "molokai.vim"
