colorscheme molokai
filetype  on
filetype plugin indent on
"set guifont=Monaco 
set nocompatible
set number
set history=2000
set autoread
set nobackup
set noswapfile
set cursorline
set cursorcolumn
set mouse=a
set ruler
set showmode 
set showmatch
set hls
set smartcase
set autoindent
set cindent
set scrolloff=3
set smartindent
set tabstop=4
set shiftwidth=4
set et
set smarttab
set lbr
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set helplang=cn
set termencoding=utf-8
set ffs=unix,dos,mac
set formatoptions+=m
set completeopt=longest,menu
set wildmenu
set background=dark
set t_Co=256
set backspace=indent,eol,start
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set hlsearch
set report=0
set laststatus=2
set cmdheight=2
set magic
